version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: inflearn-clone-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prismapass
      POSTGRES_DB: inflearn_clone
    volumes:
      - inflearn_clone_db:/var/lib/postgresql  # 버전업으로 인한 경로 변경

volumes:
  inflearn_clone_db:
